name: main

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use
        type: string
      registry-url:
        description: NPM registry URL to use
        type: string

    secrets:
      NODE_AUTH_TOKEN:
        description: Node auth token to use to install dependencies from GPR
      SSH_PRIVATE_KEY:
        description: SSH private key for git dependencies

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      packages: read

    steps:
      # Init
      - name: init
        uses: Mafalda-SFU/Github-Actions-init@v1
        with:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run tests
      - name: Run tests
        run: |
          # No tests, build package instead as a basic test and to publish it
          if node -p "require('./package.json').scripts.test" &> /dev/null ; then
            npm run build

          # Jest test runner
          elif npm list jest >/dev/null 2>&1; then
            npm install --no-save --verbose \
              @matteoh2o1999/github-actions-jest-reporter

            npm test -- \
              --reporters=@matteoh2o1999/github-actions-jest-reporter

          # Node.js built-in test runner
          else
            npm install --no-save --verbose \
              node-test-github-reporter

            NODE_OPTIONS=`echo "
              --test-reporter=spec
                --test-reporter-destination=stdout
              --test-reporter=node-test-github-reporter
                --test-reporter-destination=stderr
            " | tr -d '\r\n'` \
              npm test
          fi
