name: main

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use
        type: string
      registry-url:
        description: NPM registry URL to use
        type: string

    secrets:
      NODE_AUTH_TOKEN:
        description: Node auth token to use to install dependencies from GPR
      SSH_PRIVATE_KEY:
        description: SSH private key for git dependencies

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      packages: read

    steps:
      # Init
      - name: init
        uses: Mafalda-SFU/Github-Actions-init@v1
        with:
          node_auth_token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run tests
      - name: Run tests
        uses: Mafalda-SFU/Github-Actions-run-tests@v1
